# Generated by Django 4.1 on 2025-01-02 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='note',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
            ],
        ),
    ]
