# Generated by Django 4.1 on 2025-01-30 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_notification_alter_login_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass_request',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='parent',
            fields=[
                ('parent_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher')),
            ],
        ),
    ]
