# Generated by Django 4.1 on 2025-01-31 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_pass_request_status_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('assign_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
    ]
