# Generated by Django 4.1 on 2025-01-31 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_assignment_subject_assignment_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='student',
        ),
        migrations.AddField(
            model_name='assignment',
            name='deadline',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='assign_submiss',
            fields=[
                ('submiss_id', models.AutoField(primary_key=True, serialize=False)),
                ('submiss_date', models.CharField(max_length=100)),
                ('assign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
    ]
