# Generated by Django 4.1 on 2025-02-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_assignment_student_assignment_deadline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pass_request',
            old_name='start_state',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='pass_request',
            old_name='end_date',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='assign_submiss',
            name='file',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pass_request',
            name='start_time',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
