# Generated by Django 4.1 on 2025-02-06 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_start_state_pass_request_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('upload_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('assignement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.assignment')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
    ]
