# Generated by Django 4.1 on 2025-02-06 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='student_id',
            new_name='student',
        ),
    ]
